### ISSUE TITLE
Cannot load blender model

### ISSUE THREAD

**Issue by TayIorSwift** [ScreteMonge/creators-kit#4]
In the Model Organiser there's an option to load a model exported from blender, I've tried exporting in Obj, Fbx, Stl and even just using the .blend file itself, the error I recieve is 

Failed to find blender file. Exception: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 3 column 1 path $

am I misunderstanding how this feature should work or is this feature not working?

**Comment by ScreteMonge** [comment]
This feature isn't really for public use yet, as while I can import static models, they do not animate well. 

There's a specific string of code that's used in Blender to turn the obj into a usable file. I haven't made it public due to the above and the confusion/frustration it might cause for the average user if their imported model doesn't animate.

If you're interested, I'd be willing to share it, just know it has quite a few limitations at this time.

Also, it might be easier to reach me through discord, as I don't watch github too closely. https://discord.gg/DSpPfC2Ebh

**Comment by TayIorSwift** [comment]
Would love to get a quick rundown on how you turn it into a usable file, I've joined your discord for any future inquiries

**Comment by ScreteMonge** [comment]
[Blender Export 3.txt](https://github.com/ScreteMonge/creators-kit/files/14605101/Blender.Export.3.txt)

Here's a file with the appropriate code. Copy all the text within, then in Blender, open the Python Console editor and paste it there. It should open a dialogue prompt asking where to save the json file. You can save it anywhere, but Creator's Kit will automatically search for C:\Users\YourName\.runelite\creatorskit\blender-models so I always save it there
